"""add drive_folders and drive_files tables

Revision ID: 3584d4ab05af
Revises: c90baee5d18d
Create Date: 2025-12-22 20:22:44.153759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3584d4ab05af'
down_revision: Union[str, Sequence[str], None] = 'c90baee5d18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_folders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('google_folder_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_folder_id')
    )
    op.create_index(op.f('ix_drive_folders_owner_id'), 'drive_folders', ['owner_id'], unique=False)
    op.create_table('drive_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('google_file_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('md5_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REMOVED', name='drivefilestatus'), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['drive_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drive_files_folder_id'), 'drive_files', ['folder_id'], unique=False)
    op.create_index('ix_drive_files_folder_status', 'drive_files', ['folder_id', 'status'], unique=False)
    op.create_index(op.f('ix_drive_files_google_file_id'), 'drive_files', ['google_file_id'], unique=False)
    op.create_index(op.f('ix_drive_files_status'), 'drive_files', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drive_files_status'), table_name='drive_files')
    op.drop_index(op.f('ix_drive_files_google_file_id'), table_name='drive_files')
    op.drop_index('ix_drive_files_folder_status', table_name='drive_files')
    op.drop_index(op.f('ix_drive_files_folder_id'), table_name='drive_files')
    op.drop_table('drive_files')
    op.drop_index(op.f('ix_drive_folders_owner_id'), table_name='drive_folders')
    op.drop_table('drive_folders')
    # ### end Alembic commands ###
