"""add archived field to jobs

Revision ID: 3621727c113d
Revises: 179414c0c04d
Create Date: 2026-01-27 11:28:10.192888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3621727c113d'
down_revision: Union[str, Sequence[str], None] = '179414c0c04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('archived', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_jobs_archived'), 'jobs', ['archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_archived'), table_name='jobs')
    op.drop_column('jobs', 'archived')
    # ### end Alembic commands ###
