"""add unique constraint to drive_files

Revision ID: 37b83d124c0f
Revises: cbf03efd1c0b
Create Date: 2025-12-22 21:13:19.060034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b83d124c0f'
down_revision: Union[str, Sequence[str], None] = 'cbf03efd1c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_drive_files_folder_google_file', 'drive_files', ['folder_id', 'google_file_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_drive_files_folder_google_file', 'drive_files', type_='unique')
    # ### end Alembic commands ###
