"""add drive_file_id to documents

Revision ID: 601a3f1f225c
Revises: 7805d00d9c24
Create Date: 2025-12-27 11:09:55.072933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601a3f1f225c'
down_revision: Union[str, Sequence[str], None] = '7805d00d9c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('drive_file_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'drive_file_id')
    # ### end Alembic commands ###
