"""add author and review fields to documents

Revision ID: 7805d00d9c24
Revises: 37b83d124c0f
Create Date: 2025-12-26 18:44:15.058280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7805d00d9c24'
down_revision: Union[str, Sequence[str], None] = '37b83d124c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('author', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('needs_review', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('documents', sa.Column('review_reasons', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('original_metadata', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('reviewed_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['reviewed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'reviewed_by_id')
    op.drop_column('documents', 'reviewed_at')
    op.drop_column('documents', 'original_metadata')
    op.drop_column('documents', 'review_reasons')
    op.drop_column('documents', 'needs_review')
    op.drop_column('documents', 'author')
    # ### end Alembic commands ###
