"""add log_level enum and indexes

Revision ID: c90baee5d18d
Revises: d73af329d585
Create Date: 2025-12-22 19:42:01.148239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90baee5d18d'
down_revision: Union[str, Sequence[str], None] = 'd73af329d585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    loglevel_enum = sa.Enum('INFO', 'WARN', 'ERROR', name='loglevel')
    loglevel_enum.create(op.get_bind(), checkfirst=True)

    # Convert existing values to uppercase to match enum values
    op.execute("UPDATE job_logs SET level = UPPER(level)")

    # Alter column to use the enum type
    op.alter_column('job_logs', 'level',
               existing_type=sa.VARCHAR(length=10),
               type_=loglevel_enum,
               existing_nullable=False,
               postgresql_using='level::loglevel')
    op.create_index(op.f('ix_job_logs_created_at'), 'job_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_logs_level'), 'job_logs', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_logs_level'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_created_at'), table_name='job_logs')
    op.alter_column('job_logs', 'level',
               existing_type=sa.Enum('INFO', 'WARN', 'ERROR', name='loglevel'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # Drop the enum type
    loglevel_enum = sa.Enum('INFO', 'WARN', 'ERROR', name='loglevel')
    loglevel_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
