"""update drive models consistency

Revision ID: cbf03efd1c0b
Revises: 3584d4ab05af
Create Date: 2025-12-22 20:26:37.594653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf03efd1c0b'
down_revision: Union[str, Sequence[str], None] = '3584d4ab05af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drive_files', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drive_files', 'updated_at')
    # ### end Alembic commands ###
